--SELECT URI FROM HIT GROUP BY URI HAVING COUNT(URI) = 5


DROP TABLE IF EXISTS HIT;
DROP TABLE IF EXISTS STATS;

CREATE TABLE IF NOT EXISTS HIT (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   app VARCHAR(255) NOT NULL,
                                   uri VARCHAR(255) NOT NULL,
                                   ip VARCHAR(255) NOT NULL,
                                   timestamp TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STATS (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     app VARCHAR(255) NOT NULL,
                                     uri VARCHAR(255) NOT NULL,
                                     hits INTEGER
);

//select DISTINCT URI from HIT;
//SELECT * FROM HIT GROUP BY URI,ID HAVING COUNT(URI) = 1;
//select app,URI, count(*) as h from HIT group by URI order by count(*) desc ;
//select app,URI, count(URI) as hits from HIT group by URI having count(URI) = true;
