DROP TABLE IF EXISTS HIT;
DROP TABLE IF EXISTS STATS;

CREATE TABLE IF NOT EXISTS HIT
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                            NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP
);

CREATE TABLE IF NOT EXISTS STATS
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app  VARCHAR(255)                            NOT NULL,
    uri  VARCHAR(255)                            NOT NULL,
    hits INTEGER
);



select app, uri, count(ip)
from HIT
where timestamp >= '2020-05-05'
  and timestamp <= '2023-05-05'
  and ((uri = '/events/1')
    or (uri = '/events/2')
    or (uri = '/events/3')
    or (uri = '/event/658')
    or (uri = '/event/361'))
group by uri, app;

select app, uri, count(ip)
from HIT
where timestamp >= '2020-05-05'
  and timestamp <= '2023-05-05'
  and ((uri = '/events/1')
    or (uri = '/events/2')
    or (uri = '/events/3')
    or (uri = '/event/658')
    or (uri = '/event/361'))
group by uri, app
having count(ip) = 1;
